WINDOW_SIZE = WINDOW_W, WINDOW_H = 640, 480

CELL_SIZE = 30
CELL_ROWS = WINDOW_H // CELL_SIZE
CELL_COLS = WINDOW_W // CELL_SIZE

BACKGROUND_COLOR = (120,) * 3
GAMEBOARD_GRID_COLOR = (172,) * 3
SNAKE_COLOR = "white"
FOOD_COLOR = "red"